language: python
notifications:
  email: false
sudo: false
cache: pip
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- make install
script:
- make test
deploy:
  provider: pypi
  user: evhub-develop
  password:
    secure: bUn5KVs6OfZO+jT+bLReoreKlRFWXCyEsas89A+23ZrlUhb+yM71TBewdqTPq3Q2dDVC5noVFDso4rCtEoS8gemedGNOhSDMaO5oD55hrtxN7nL2MG+HJkbvMRR50ZF/oDzSrmaTJc+HXEDoPk/IPxOWWXDE3hjBmtlFM8NN4+kkOuvd4aeru6CvDnJQhB9bNpN/zO1mZntYq0TD6G0B6okSUR90jEprxU+qHumHPS2Zoxh6fyPL56kxN6D90Sz9ZAOhQnJYcwLH/DMOUxzSxwMKfoRh+AHiMe3Y+RSim57UNUVQM5cZ0Ps6U8q5bEoIsakA2YbV4rvAy4DX9emK5+6jbEcLyvvU6HYL3kO+rQQHSpsyn1SSORUMCjgxH88nds3x+9ZGaXOlXkY22JUItYBhaW1Zd4BVYxUn0u1E5CRZ5YG+XjR+gpuF2ttOfCTV4/gJxXYEWmElIkLKi/y8hAmfGpLsMSwQGVeWsf2h4z6B5u2UTAIz/5+OZZ9eM5HKsiwAtpK8vOxBFynS4HD13X2bfirzQggTCfRqymv9C8gXODWd4WHBJFD6f35GGHDqu96FkUlyxuXRMvPVkdJKuGPJqc4xWDsB0oWRrIs22AfX+cpWcT+5kUfV2iIPVl9PzcwUJwA0o6vtejICvH4i2Rzd+Zfk641bHysGisjF7n0=
  on:
    distributions: sdist bdist_wheel
    repo: evhub/cpyparsing
    branch: master
